### ISSUE TITLE
Houses POST failing tests

### ISSUE THREAD

**Issue by JacksonDagger** [JacksonDagger/OneRoof#66]
` 

FAIL  tests/routes.test.js
  ● Console

    console.log
      Doing fake login for uid: foo

      at noAuthMiddleware (auth.js:33:13)

    console.log
      Uid:  foo

      at routes/houses.js:20:13

    console.log
      [Error: select `roommate_id` from `roommates` where `roommate_uid` = 'foo' - SQLITE_ERROR: no such table: roommates] {
        errno: 1,
        code: 'SQLITE_ERROR'
      }`

**Comment by maddie1202** [comment]
Did you try this?
```
knex migrate:rollback --all
knex migrate:latest
knex seed:run
```

**Comment by JacksonDagger** [comment]
@maddie1202 still broken
